remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-them
title: Today I Learn
url: https://luong213.github.io
search_enabled: false
footer_content: "Copyright &copy; 2023 Luong Vu"
gh_edit_link: false
gh_edit_link_text: "Edit this page on GitHub."
